# Generated by Django 5.0.2 on 2024-02-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'blank': 'The name cannot be blank.', 'invalid': 'Invalid value for the name.', 'max_length': 'The name must be 100 characters or less.', 'null': 'The name cannot be empty.', 'required': 'The name is required.', 'unique': 'The name must be unique.'}, max_length=100, unique=True)),
                ('website', models.URLField(error_messages={'blank': 'The website cannot be blank.', 'max_length': 'The website must be 200 characters or less.', 'required': 'The website is required.'})),
                ('image', models.ImageField(error_messages={'blank': 'The image cannot be empty.', 'required': 'The image is required.'}, upload_to='sponsors')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
