# Generated by Django 5.0.2 on 2024-02-25 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsors',
            options={'verbose_name_plural': 'Sponsors'},
        ),
    ]
