# Generated by Django 5.0.2 on 2024-02-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_alter_sponsors_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='image',
            field=models.ImageField(blank=True, default=None, error_messages={'blank': 'The image cannot be empty.', 'required': 'The image is required.'}, null=True, upload_to='sponsors'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='website',
            field=models.URLField(blank=True, default=None, error_messages={'blank': 'The website cannot be blank.', 'max_length': 'The website must be 200 characters or less.', 'required': 'The website is required.'}, null=True),
        ),
    ]
