# Generated by Django 5.0.2 on 2024-02-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0003_alter_sponsors_image_alter_sponsors_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='sponsor_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('additional', 'Additional')], default='additional', error_messages={'blank': 'The sponsor type cannot be blank.', 'choices': 'The choices for sponsor type must be either primary, secondary, or additional.', 'max_length': 'The sponsor type must be 10 characters or less.', 'required': 'The sponsor type is required.'}, max_length=10),
        ),
    ]
