# Generated by Django 5.0.2 on 2024-03-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(error_messages={'blank': 'The question cannot be blank.', 'invalid': 'Invalid value for the question.', 'max_length': 'The question must be 100 characters or less.', 'null': 'The question cannot be empty.', 'required': 'The question is required.', 'unique': 'The question must be unique.'}, max_length=100, unique=True)),
                ('answer', models.CharField(error_messages={'blank': 'The answer cannot be blank.', 'invalid': 'Invalid value for the answer.', 'max_length': 'The answer must be 300 characters or less.', 'null': 'The answer cannot be empty.', 'required': 'The answer is required.'}, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
            },
        ),
    ]
